export const GET_FOLLOWS_REQUEST = 'GET_FOLLOWS_REQUEST'
export const GET_FOLLOWS_SUCCESS = 'GET_FOLLOWS_SUCCESS'
export const GET_FOLLOWS_FAIL = 'GET_FOLLOWS_FAIL'

export const FOLLOW_REQUEST = 'FOLLOW_REQUEST'
export const FOLLOW_SUCCESS = 'FOLLOW_SUCCESS'
export const FOLLOW_FAIL = 'FOLLOW_FAIL'

export const UNFOLLOW_REQUEST = 'UNFOLLOW_REQUEST'
export const UNFOLLOW_SUCCESS = 'UNFOLLOW_SUCCESS'
export const UNFOLLOW_FAIL = 'UNFOLLOW_FAIL'

