export const GET_CARTITEMS_REQUEST = 'GET_CARTITEMS_REQUEST'
export const GET_CARTITEMS_SUCCESS = 'GET_CARTITEMS_SUCCESS'
export const GET_CARTITEMS_FAIL = 'GET_CARTITEMS_FAIL'

export const CREATE_CART_REQUEST = 'CREATE_CART_REQUEST'
export const CREATE_CART_SUCCESS = 'CREATE_CART_SUCCESS'
export const CREATE_CART_FAIL = 'CREATE_CART_FAIL'

export const ADD_TO_CART_REQUEST = 'ADD_TO_CART_REQUEST'
export const ADD_TO_CART_SUCCESS = 'ADD_TO_CART_SUCCESS'
export const ADD_TO_CART_FAIL = 'ADD_TO_CART_FAIL'

export const DELETE_CARTITEM_REQUEST = 'DELETE_CARTITEM_REQUEST'
export const DELETE_CARTITEM_SUCCESS = 'DELETE_CARTITEM_SUCCESS'
export const DELETE_CARTITEM_FAIL = 'DELETE_CARTITEM_FAIL'

export const UPDATE_ORDERITEM_QTY_REQUEST = 'UPDATE_ORDERITEM_QTY_REQUEST'
export const UPDATE_ORDERITEM_QTY_SUCCESS = 'UPDATE_ORDERITEM_QTY_SUCCESS'
export const UPDATE_ORDERITEM_QTY_FAIL = 'UPDATE_ORDERITEM_QTY_FAIL'

export const DELETE_ORDERITEM_REQUEST = 'DELETE_ORDERITEM_REQUEST'
export const DELETE_ORDERITEM_SUCCESS = 'DELETE_ORDERITEM_SUCCESS'
export const DELETE_ORDERITEM_FAIL = 'DELETE_ORDERITEM_FAIL'

export const CHECKOUT = 'CHECKOUT'

export const GET_ORDER_LIST_REQUEST = 'GET_ORDER_LIST_REQUEST'
export const GET_ORDER_LIST_SUCCESS = 'GET_ORDER_LIST_SUCCESS'
export const GET_ORDER_LIST_FAIL = 'GET_ORDER_LIST_FAIL'

export const CREATE_ORDER_REQUEST = 'CREATE_ORDER_REQUEST'
export const CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS'
export const CREATE_ORDER_FAIL = 'CREATE_ORDER_FAIL'

export const GET_ORDER_REQUEST = 'GET_ORDER_REQUEST'
export const GET_ORDER_SUCCESS = 'GET_ORDER_SUCCESS'
export const GET_ORDER_FAIL = 'GET_ORDER_FAIL'

export const CANCEL_ORDER_REQUEST = 'CANCEL_ORDER_REQUEST'
export const CANCEL_ORDER_SUCCESS = 'CANCEL_ORDER_SUCCESS'
export const CANCEL_ORDER_FAIL = 'CANCEL_ORDER_FAIL'

export const DELIVER_ORDER_REQUEST = 'DELIVER_ORDER_REQUEST'
export const DELIVER_ORDER_SUCCESS = 'DELIVER_ORDER_SUCCESS'
export const DELIVER_ORDER_FAIL = 'DELIVER_ORDER_FAIL'
