export const GET_DISCOVER_POSTS_REQUEST = 'GET_DISCOVER_POSTS_REQUEST'
export const GET_DISCOVER_POSTS_SUCCESS = 'GET_DISCOVER_POSTS_SUCCESS'
export const GET_DISCOVER_POSTS_FAIL = 'GET_DISCOVER_POSTS_FAIL'

export const GET_FOLLOWINGS_POSTS_REQUEST = 'GET_FOLLOWINGS_POSTS_REQUEST'
export const GET_FOLLOWINGS_POSTS_SUCCESS = 'GET_FOLLOWINGS_POSTS_SUCCESS'
export const GET_FOLLOWINGS_POSTS_FAIL = 'GET_FOLLOWINGS_POSTS_FAIL'

export const GET_POST_REQUEST = 'GET_POST_REQUEST'
export const GET_POST_SUCCESS = 'GET_POST_SUCCESS'
export const GET_POST_FAIL = 'GET_POST_FAIL'

export const GET_HOME_POST_REQUEST = 'GET_HOME_POST_REQUEST'
export const GET_HOME_POST_SUCCESS = 'GET_HOME_POST_SUCCESS'
export const GET_HOME_POST_FAIL = 'GET_HOME_POST_FAIL'

export const CREATE_POST_REQUEST = 'CREATE_POST_REQUEST'
export const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS'
export const CREATE_POST_FAIL = 'CREATE_POST_FAIL'

export const UPDATE_POST_REQUEST = 'UPDATE_POST_REQUEST'
export const UPDATE_POST_SUCCESS = 'UPDATE_POST_SUCCESS'
export const UPDATE_POST_FAIL = 'UPDATE_POST_FAIL'

export const DELETE_POST_REQUEST = 'DELETE_POST_REQUEST'
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS'
export const DELETE_POST_FAIL = 'DELETE_POST_FAIL'

export const LIKE_POST_REQUEST = 'LIKE_POST_REQUEST'
export const LIKE_POST_SUCCESS = 'LIKE_POST_SUCCESS'
export const LIKE_POST_FAIL = 'LIKE_POST_FAIL'

export const UNLIKE_POST_REQUEST = 'UNLIKE_POST_REQUEST'
export const UNLIKE_POST_SUCCESS = 'UNLIKE_POST_SUCCESS'
export const UNLIKE_POST_FAIL = 'UNLIKE_POST_FAIL'

export const GET_SEARCH_POST_REQUEST = 'GET_SEARCH_POST_REQUEST'
export const GET_SEARCH_POST_SUCCESS = 'GET_SEARCH_POST_SUCCESS'
export const GET_SEARCH_POST_FAIL = 'GET_SEARCH_POST_FAIL'