export const CREATE_REVIEW_REQUEST = 'CREATE_REVIEW_REQUEST'
export const CREATE_REVIEW_SUCCESS = 'CREATE_REVIEW_SUCCESS'
export const CREATE_REVIEW_FAIL = 'CREATE_REVIEW_FAIL'

export const EDIT_REVIEW_REQUEST = 'EDIT_REVIEW_REQUEST'
export const EDIT_REVIEW_SUCCESS = 'EDIT_REVIEW_SUCCESS'
export const EDIT_REVIEW_FAIL = 'EDIT_REVIEW_FAIL'

export const DELETE_REVIEW_REQUEST = 'DELETE_REVIEW_REQUEST'
export const DELETE_REVIEW_SUCCESS = 'DELETE_REVIEW_SUCCESS'
export const DELETE_REVIEW_FAIL = 'DELETE_REVIEW_FAIL'